### ISSUE TITLE
CH546 usb.core.USBTimeoutError: [Errno 110] Operation timed out Segmentation fault

### ISSUE THREAD

**Issue by ruben-herold** [fossasia/led-name-badge-ls32#11]
hi,

try to use it on CH546 devices on Ubuntu 24 ends in Segmentation fault:
```

Module usb.core detected
Type: 11x44
Libusb device initialized
Write using wch.cn - CH546 (bus=3 dev=60 endpoint=2) via libusb
Traceback (most recent call last):
  File "/home/ruben/daten/led-badge/fossasia/led-name-badge-ls32/./led-badge-11x44.py", line 4, in <module>
    lednamebadge.main()
  File "/home/ruben/daten/led-badge/fossasia/led-name-badge-ls32/lednamebadge.py", line 1135, in main
    LedNameBadge.write(buf, method, args.device_id)
  File "/home/ruben/daten/led-badge/fossasia/led-name-badge-ls32/lednamebadge.py", line 828, in write
    write_method.write(buf)
  File "/home/ruben/daten/led-badge/fossasia/led-name-badge-ls32/lednamebadge.py", line 539, in write
    self._write(buf)
  File "/home/ruben/daten/led-badge/fossasia/led-name-badge-ls32/lednamebadge.py", line 664, in _write
    self.endpoint.write(buf[i * 64:i * 64 + 64])
  File "/usr/lib/python3/dist-packages/usb/core.py", line 408, in write
    return self.device.write(self, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/usb/core.py", line 989, in write
    return fn(
           ^^^
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 855, in intr_write
    return self.__write(self.lib.libusb_interrupt_transfer,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 938, in __write
    _check(retval)
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 602, in _check
    raise USBTimeoutError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBTimeoutError: [Errno 110] Operation timed out
Segmentation fault

```

**Comment by pfennig42** [comment]
I can second this. It always happens, when the text gets longer than the screen width. 
For some reason, it also crashes with some letters (e.g. b or i)

Edit: This fork worked: https://github.com/drizzt/led-name-badge-ls32/tree/master, at least when plugging it in the first time

**Comment by Sandr0x00** [comment]
here's a PR for fixing it on the current master version of this repository instead of an outdated version.
https://github.com/fossasia/led-name-badge-ls32/pull/12
